import path from 'node:path'

const SOURCE_ROOTS = new Set(['pipeline', 'shared', 'src', 'server', 'scripts', 'tools'])
const SOURCE_EXTENSIONS = new Set([
  '.bash',
  '.bat',
  '.c',
  '.cjs',
  '.cmd',
  '.css',
  '.cts',
  '.fish',
  '.go',
  '.gql',
  '.graphql',
  '.h',
  '.java',
  '.js',
  '.jsx',
  '.kt',
  '.kts',
  '.less',
  '.mjs',
  '.mts',
  '.php',
  '.proto',
  '.ps1',
  '.py',
  '.pyi',
  '.rb',
  '.rs',
  '.sass',
  '.scala',
  '.scss',
  '.sh',
  '.sql',
  '.svelte',
  '.swift',
  '.ts',
  '.tsx',
  '.vue',
  '.zsh',
])

const BINARY_EXTENSIONS = new Set([
  '.7z',
  '.avi',
  '.avif',
  '.bin',
  '.bmp',
  '.bz2',
  '.class',
  '.dat',
  '.db',
  '.dll',
  '.doc',
  '.docx',
  '.dylib',
  '.eot',
  '.exe',
  '.flac',
  '.gif',
  '.gz',
  '.heic',
  '.ico',
  '.jar',
  '.jpeg',
  '.jpg',
  '.m4a',
  '.mkv',
  '.mov',
  '.mp3',
  '.mp4',
  '.ogg',
  '.otf',
  '.pdf',
  '.png',
  '.ppt',
  '.pptx',
  '.pyc',
  '.rar',
  '.so',
  '.sqlite',
  '.sqlite3',
  '.tgz',
  '.ttf',
  '.wav',
  '.wasm',
  '.webm',
  '.webp',
  '.woff',
  '.woff2',
  '.xls',
  '.xlsx',
  '.xz',
  '.zip',
])

export function isSourceFile(relativePath: string, content: Buffer) {
  const root = relativePath.split('/')[0]
  if (!root || !SOURCE_ROOTS.has(root)) return false
  const extension = path.extname(relativePath).toLowerCase()
  if (SOURCE_EXTENSIONS.has(extension)) return true
  return extension === '' && content.subarray(0, 2).toString('ascii') === '#!'
}

export function shouldInspectAsText(relativePath: string) {
  return !BINARY_EXTENSIONS.has(path.extname(relativePath).toLowerCase())
}
